### PR TITLE
do not use a mirror to virtual repo /all since it is inefficient

### PR DESCRIPTION
**Pull request by r-kok**
Hopefully this will reduce chance that 504 GATEWAY TIMEOUT occurs

### CODE REVIEW

**Comment by r-kok** [comment]
example of failing build when retrieving a plugin:

https://jenkins.prod.portbase-ci.com/job/bitbucket/job/bezoekschip-service/job/master/139/console

**Comment by Thadir** [comment]
Zullen we dit mergen een vrijdag?

**Comment by melvyndekort** [comment]
@r-kok what is the status of this PR?

**Comment by r-kok** [comment]
not an issue anymore

**Pull request closed without merging**
